# Generated by Django 5.1 on 2024-08-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcertificado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.CreateModel(
            name='ProyectoVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('archivo_propuesta', models.FileField(blank=True, null=True, upload_to='propuestas_proyectos/')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
        ),
    ]
