# Generated by Django 5.1 on 2024-09-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0004_espacio_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoresidencia',
            name='documento_certificado',
            field=models.FileField(upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='certificadoresidencia',
            name='numero_certificado',
            field=models.CharField(max_length=50),
        ),
    ]
