# Generated by Django 5.1 on 2024-09-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0006_alter_solicitudcertificado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistroVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vecino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
        ),
    ]
