# Generated by Django 5.1 on 2024-10-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0009_vecino_comuna_vecino_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='precio_por_hora',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
