# Generated by Django 5.1 on 2024-10-07 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0010_espacio_precio_por_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
