# Generated by Django 5.1 on 2024-10-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0012_rename_titulo_proyectovecinal_propuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vecino',
            name='comuna',
            field=models.CharField(choices=[('ÑUÑOA', 'Ñuñoa'), ('PUENTE_ALTO', 'Puente Alto'), ('LA_FLORIDA', 'La Florida')], default='ÑUÑOA', max_length=20),
        ),
        migrations.CreateModel(
            name='AdministradorComuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(choices=[('ÑUÑOA', 'Ñuñoa'), ('PUENTE_ALTO', 'Puente Alto'), ('LA_FLORIDA', 'La Florida')], max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vecino',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vecinos', to='junta_vecinos.administradorcomuna'),
        ),
    ]
