# Generated by Django 5.1 on 2024-10-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0013_alter_vecino_comuna_administradorcomuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='junta_vecinos.administradorcomuna'),
            preserve_default=False,
        ),
    ]
