# Generated by Django 5.1 on 2024-10-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0014_espacio_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comuna',
            field=models.CharField(choices=[('ÑUÑOA', 'Ñuñoa'), ('PUENTE_ALTO', 'Puente Alto'), ('LA_FLORIDA', 'La Florida')], default='ÑUÑOA', max_length=20),
        ),
    ]
