# Generated by Django 5.1 on 2024-10-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0015_noticia_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='junta_vecinos.administradorcomuna'),
        ),
    ]
