# Generated by Django 5.1 on 2024-10-13 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0016_alter_noticia_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistrovecino',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_registro', to='junta_vecinos.administradorcomuna'),
        ),
    ]
