# Generated by Django 5.1 on 2024-10-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0017_solicitudregistrovecino_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudregistrovecino',
            name='administrador',
        ),
        migrations.CreateModel(
            name='ActividadVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('cupo_actual', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='activa', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.administradorcomuna')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.actividadvecinal')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
            options={
                'unique_together': {('actividad', 'vecino')},
            },
        ),
    ]
