# Generated by Django 5.1 on 2024-10-28 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0019_actividadvecinal_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('motivo', models.TextField(help_text='¿Por qué quieres participar en este proyecto?')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='junta_vecinos.proyectovecinal')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones_proyectos', to='junta_vecinos.vecino')),
            ],
            options={
                'unique_together': {('proyecto', 'vecino')},
            },
        ),
    ]
