# Generated by Django 5.1 on 2024-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0023_tokenregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorcomuna',
            name='presidente_apellidos',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos del Presidente'),
        ),
        migrations.AddField(
            model_name='administradorcomuna',
            name='presidente_nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del Presidente'),
        ),
        migrations.AddField(
            model_name='administradorcomuna',
            name='presidente_rut',
            field=models.CharField(default='', max_length=12, verbose_name='RUT del Presidente'),
        ),
    ]
