# Generated by Django 5.1 on 2024-11-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0026_solicitudcertificado_certificado_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcertificado',
            name='certificado_generado',
        ),
    ]
