# Generated by Django 5.1 on 2024-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0027_remove_solicitudcertificado_certificado_generado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcertificado',
            name='documento_residencia',
            field=models.ImageField(upload_to='documentos_residencia/'),
        ),
    ]
